spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    check-template: true
    check-template-location: true
    encoding: utf-8

  security:
    user:
      name: user
      password: user

  datasource:
    url: jdbc:mysql://192.168.0.12:3306/nine_sys?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

logging:
  level:
    com.nine.user.mapper: trace


