autoDetectedPackages:
- com.nine.common.constans
- com.nine.common.domain
- com.nine.common.enums
- com.nine.common.ex
- com.nine.common.filter
- com.nine.common.handler
- com.nine.common.utils.gzip
- com.nine.common.utils.resources
- com.nine.common.utils.spel
- com.nine.dao.annotation
- com.nine.dao.config
- com.nine.dao.dto
- com.nine.dao.entity
- com.nine.dao.service
- com.nine.dao.vo
- com.nine.dingtalk
- com.nine.domain.log
- com.nine.domain.user
- com.nine.gateway
- com.nine.log
- com.nine.redis.annotation
- com.nine.redis.aspects
- com.nine.redis.configure
- com.nine.redis.lock
- com.nine.redis.window
- com.nine.swagger.config
- com.nine.user
- com.nine.websocket
enableAutoDetect: true
funcDisplayConfig:
  skipConstructors: false
  skipFieldAccess: true
  skipFieldChange: true
  skipGetters: true
  skipPrivateMethods: false
  skipSetters: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: smart
startOnDebug: false
