spring:
  datasource:
    url: jdbc:mysql://192.168.0.12:3306/nine_sys?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
